apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 457472006214.dkr.ecr.us-west-1.amazonaws.com/guestbook
  newName: 457472006214.dkr.ecr.us-west-1.amazonaws.com/guestbook
  newTag: new
